/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SAR_Transactions;

import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class SAR_Transactions extends javax.swing.JFrame {

    /**
     * Creates new form Sample
     */
    public SAR_Transactions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        loadBtn = new javax.swing.JButton();
        nameFld = new javax.swing.JTextField();
        priceFld = new javax.swing.JTextField();
        dateFld = new javax.swing.JTextField();
        manuFld = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        exportRadio = new javax.swing.JRadioButton();
        importRadio = new javax.swing.JRadioButton();
        cateogarySearch = new javax.swing.JButton();
        cateogary1 = new javax.swing.JComboBox<>();
        quantityFld = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        searchFld = new javax.swing.JTextField();
        priceSearch = new javax.swing.JButton();
        importRB = new javax.swing.JRadioButton();
        exportRB = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        inputCB = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileBtn = new javax.swing.JMenu();
        openBtn = new javax.swing.JMenuItem();
        exitBtn = new javax.swing.JMenuItem();
        helpBtn = new javax.swing.JMenu();
        userGuide = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 1, true));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Wai Wai", "Import", "CG", "Food", "100", "25", "23rd DEC 2021", "2500"},
                {"Real", "Export", "Real", "Food", "300", "25", "23rd DEC 2021", "7500"},
                {"Petrol", "Import", "NOC", "Petroleum", "100", "110", "1st Jan 2022", "11000"},
                {"Dissel", "Export", "NOC", "Petroleum", "100", "110", "1st JAN 2022", "11000"},
                {"Model X", "Import", "Tesla", "Vechile", "2", "9000000", "2nd JAN 2022", "18000000"},
                {"Scorpio", "Import", "Mahindra", "Vechile", "10", "1000000", "2nd JAN 2022", "1000000"},
                {"Necklace", "Import", "FNGSDA", "Jewellery", "10", "50000", "4th JAN 2022", "500000"},
                {"Ring", "Export", "FNGSDA", "Jewellery", "11", "6000000", "4th JAN 2021", "600000"},
                {"Iphone 13", "Import", "Apple", "Gaddets", "10", "100000", "3rd JAN 2021", "1000000"},
                {"Poco X3", "Export", "Xoami", "Gagdets", "10", "50000", "4th JAN 2022", "5000000"},
                {"Jacket", "Import", "GUCCI", "Clothes", "2", "60000", "5th JAN 2022", "360000"},
                {"Pant", "Export", "Shree Raji Suppliers", "CLothes", "50", "1000", "6th JAN 2022", "50000"}
            },
            new String [] {
                "Name", "Transaction type", "Manufactured By", "Prod.Category", "Quantity", "Price per Item", "Date", "Total Price"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SAR TRANSACTIONS");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 0, 14))); // NOI18N

        loadBtn.setBackground(new java.awt.Color(51, 51, 51));
        loadBtn.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        loadBtn.setForeground(new java.awt.Color(102, 255, 255));
        loadBtn.setText("Load txt");
        loadBtn.setBorder(null);
        loadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBtnActionPerformed(evt);
            }
        });

        nameFld.setBackground(new java.awt.Color(51, 51, 51));
        nameFld.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nameFld.setForeground(new java.awt.Color(255, 255, 255));
        nameFld.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 1, 14), new java.awt.Color(153, 255, 255))); // NOI18N
        nameFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFldActionPerformed(evt);
            }
        });
        nameFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameFldKeyPressed(evt);
            }
        });

        priceFld.setBackground(new java.awt.Color(51, 51, 51));
        priceFld.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        priceFld.setForeground(new java.awt.Color(255, 255, 255));
        priceFld.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Price per Item", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 1, 14), new java.awt.Color(153, 255, 255))); // NOI18N
        priceFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                priceFldKeyPressed(evt);
            }
        });

        dateFld.setBackground(new java.awt.Color(51, 51, 51));
        dateFld.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        dateFld.setForeground(new java.awt.Color(255, 255, 255));
        dateFld.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Date", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 1, 14), new java.awt.Color(153, 255, 255))); // NOI18N

        manuFld.setBackground(new java.awt.Color(51, 51, 51));
        manuFld.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        manuFld.setForeground(new java.awt.Color(255, 255, 255));
        manuFld.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Manufactured By", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 1, 14), new java.awt.Color(153, 255, 255))); // NOI18N
        manuFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuFldActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(51, 51, 51));
        updateBtn.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(102, 255, 255));
        updateBtn.setText("UPDATE");
        updateBtn.setBorder(null);
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(51, 51, 51));
        clearBtn.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(102, 255, 255));
        clearBtn.setText("CLEAR");
        clearBtn.setBorder(null);
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 255, 255)));

        exportRadio.setBackground(new java.awt.Color(102, 102, 102));
        buttonGroup1.add(exportRadio);
        exportRadio.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        exportRadio.setForeground(new java.awt.Color(255, 255, 255));
        exportRadio.setText("Export");
        exportRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportRadioActionPerformed(evt);
            }
        });

        importRadio.setBackground(new java.awt.Color(102, 102, 102));
        buttonGroup1.add(importRadio);
        importRadio.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        importRadio.setForeground(new java.awt.Color(255, 255, 255));
        importRadio.setText("Import");
        importRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importRadioActionPerformed(evt);
            }
        });

        cateogarySearch.setBackground(new java.awt.Color(51, 51, 51));
        cateogarySearch.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        cateogarySearch.setForeground(new java.awt.Color(102, 255, 255));
        cateogarySearch.setText("SEARCH");
        cateogarySearch.setBorder(null);
        cateogarySearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cateogarySearchActionPerformed(evt);
            }
        });

        cateogary1.setBackground(new java.awt.Color(51, 51, 51));
        cateogary1.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        cateogary1.setForeground(new java.awt.Color(153, 153, 153));
        cateogary1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food", "Petroleum", "Vechile", "Jewellery", "Gagdets", "Clothes" }));
        cateogary1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cateogary1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(importRadio)
                            .addComponent(exportRadio)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(cateogarySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(162, Short.MAX_VALUE)
                    .addComponent(cateogary1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(12, 12, 12)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(importRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exportRadio)
                .addGap(39, 39, 39)
                .addComponent(cateogarySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(cateogary1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(88, Short.MAX_VALUE)))
        );

        quantityFld.setBackground(new java.awt.Color(51, 51, 51));
        quantityFld.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        quantityFld.setForeground(new java.awt.Color(255, 255, 255));
        quantityFld.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quantity", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 1, 14), new java.awt.Color(153, 255, 255))); // NOI18N
        quantityFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityFldActionPerformed(evt);
            }
        });
        quantityFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                quantityFldKeyPressed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 1, true));

        searchFld.setBackground(new java.awt.Color(51, 51, 51));
        searchFld.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        searchFld.setForeground(new java.awt.Color(255, 255, 255));
        searchFld.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Price", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 1, 14), new java.awt.Color(153, 255, 255))); // NOI18N
        searchFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFldActionPerformed(evt);
            }
        });
        searchFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchFldKeyPressed(evt);
            }
        });

        priceSearch.setBackground(new java.awt.Color(153, 153, 153));
        priceSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SAR_Transactions/50.png"))); // NOI18N
        priceSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));
        priceSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchFld, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(priceSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(priceSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(searchFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        importRB.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup2.add(importRB);
        importRB.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        importRB.setForeground(new java.awt.Color(51, 255, 255));
        importRB.setText("Import");
        importRB.setActionCommand("Import");

        exportRB.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup2.add(exportRB);
        exportRB.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        exportRB.setForeground(new java.awt.Color(51, 255, 255));
        exportRB.setText("Export");
        exportRB.setActionCommand("Export");

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 255));
        jLabel2.setText("Transaction Type");

        inputCB.setBackground(new java.awt.Color(0, 0, 0));
        inputCB.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        inputCB.setForeground(new java.awt.Color(102, 255, 255));
        inputCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food", "Petroleum", "Vechile", "Jewellery", "Gagdets", "Clothes" }));
        inputCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCBActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 255));
        jLabel3.setText("Prod.Category");

        addBtn.setBackground(new java.awt.Color(51, 51, 51));
        addBtn.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        addBtn.setForeground(new java.awt.Color(102, 255, 255));
        addBtn.setText("ADD");
        addBtn.setBorder(null);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(325, 325, 325))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(loadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(inputCB, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(jLabel3)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel2)
                                .addGap(81, 81, 81))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(importRB)
                                        .addGap(18, 18, 18)
                                        .addComponent(exportRB))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(manuFld, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(48, 48, 48)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quantityFld, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateFld, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceFld, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(loadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(importRB)
                            .addComponent(exportRB))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dateFld, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantityFld, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manuFld, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(priceFld, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputCB, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(102, 102, 102));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));
        jMenuBar1.setForeground(new java.awt.Color(102, 102, 102));

        fileBtn.setText("File");

        openBtn.setText("Open");
        openBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBtnActionPerformed(evt);
            }
        });
        fileBtn.add(openBtn);

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        fileBtn.add(exitBtn);

        jMenuBar1.add(fileBtn);

        helpBtn.setText("Help");
        helpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpBtnActionPerformed(evt);
            }
        });

        userGuide.setText("User Guide");
        userGuide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userGuideActionPerformed(evt);
            }
        });
        helpBtn.add(userGuide);

        jMenuBar1.add(helpBtn);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 121, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exportRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportRadioActionPerformed
        // TODO add your handling code here:
        exportRadio.setActionCommand("Export");
    }//GEN-LAST:event_exportRadioActionPerformed

    private void importRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importRadioActionPerformed
        // TODO add your handling code here:
        importRadio.setActionCommand("Import");

    }//GEN-LAST:event_importRadioActionPerformed

    private void searchFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFldActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void inputCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCBActionPerformed

    private void loadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBtnActionPerformed
        // TODO add your handling code here:
        String path = "E:\\Year 2\\Sem 1\\Emerging Programming Platforms and Technologies\\Coursework 1\\SAR_Transactions\\data.txt"; // the path of the required file
        File file = new File(path); // creating a file for the given fath

        try {
            //file reader to read the file required
            FileReader fReader = new FileReader(file);
            BufferedReader bReader = new BufferedReader(fReader);   //buffer reader to read what's in the file

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();        //default table model to identify our jtable and to add more functions
            Object[] lines = bReader.lines().toArray();        //table is all in object so creatring object datatype 

            for (int i = 0; i < lines.length; i++) {         //for loop utilization
                String[] row = lines[i].toString().split(",");      //spliting the data in the file into different parts
                model.addRow(row);          //adding the separated data in out jtable.
            }
            JOptionPane.showMessageDialog(null, "Transactions added successfully.");

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "File not found",
                    "Error!!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_loadBtnActionPerformed

    private void quantityFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityFldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_quantityFldActionPerformed

    private void priceSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceSearchActionPerformed
        // TODO add your handling code here:
        try {
            ArrayList<Integer> totalPrice = new ArrayList();   //creating new Arraylist
            ArrayList<String> all = getValue();                //getting all the table data from getValue() method
            int a = 7;
            for (int i = 0; i < all.size() / 8; i++) {        //getting values of total price and add to totalPrice Arraylist
                totalPrice.add(Integer.parseInt(all.get(a)));
                a += 8;
            }
            ArrayList<Integer> sorted = SortSearch.sort(totalPrice, all);   //passing the arrys to Sort Search class for sorting 

            SortSearch.binarySearch(sorted, Integer.parseInt(searchFld.getText())); // passing the arrys to Sort Search class for searching

            int b = 7;

            for (int i = 0; i < all.size() / 8; i++) {                             //displaying the item with the searched price
                if (all.get(b).equals(searchFld.getText())) {
                    JOptionPane.showMessageDialog(null, "The item with price as " + searchFld.getText() + " is " + all.get(b - 7));
                    break;
                }
                b += 8;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please enter the searching price.");
        }
    }//GEN-LAST:event_priceSearchActionPerformed
    public void check(String cateogary, String transactionType) {            //method to check whether the input cateogary exsist in table and display their details
        ArrayList<String> hero = getValue();
        int a = 1;
        int b = 3;
        ArrayList<String> value = new ArrayList();
        for (int i = 0; i < hero.size() / 8; i++) {                           //checking the input
            int c = a;
            if (transactionType.equals(hero.get(a)) && cateogary.equals(hero.get(b))) {
                value.add(hero.get(a - 1));
                for (int j = 0; j <= 6; j++) {
                    value.add(hero.get(c++));                                //all values are stored in the value arraylist
                }
            }
            a += 8;
            b += 8; 
        }
        if (value.isEmpty()) {                                                //if their are no such values
            JOptionPane.showMessageDialog(null, "No such values are present in the table");
        } else {                                                              //if their exsist such value search and display their names
            int d = 0;
            String allItems = "";
            for (int i = 0; i < value.size() / 8; i++) {
                allItems += value.get(d) + " , ";
                d += 8;
            }

            JOptionPane.showMessageDialog(null, "The items which are"
                    + " " + transactionType + "ed " + " and is of " + cateogary + " cateogary " + " are " + allItems);
            value.clear();
        }

    }

    public ArrayList getValue() {                                              //method to store all the values of table into arraylist
        ArrayList<String> data = new ArrayList();
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            for (int j = 0; j < jTable1.getColumnCount(); j++) {
                data.add((String) jTable1.getValueAt(i, j));
            }
        }
        return data;
    }

    private void cateogarySearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cateogarySearchActionPerformed
        // TODO add your handling code here:
        try {

            String transactionType = buttonGroup1.getSelection().getActionCommand();
            String productCateogary = cateogary1.getSelectedItem().toString();
            if ("Import".equals(transactionType)) {                           //passing values to check method for checking the availability of passed values
                if ("Food".equals(productCateogary)) {
                    check("Food", "Import");
                } else if ("Vechile".equals(productCateogary)) {
                    check("Vechile", "Import");
                } else if ("Petroleum".equals(productCateogary)) {
                    check("Petroleum", "Import");
                } else if ("Jewellery".equals(productCateogary)) {
                    check("Jewellery", "Import");
                } else if ("Gagdets".equals(productCateogary)) {
                    check("Gagdets", "Import");
                } else if ("Clothes".equals(productCateogary)) {
                    check("Clothes", "Import");
                }

            } else if ("Export".equals(transactionType)) {
                if ("Food".equals(productCateogary)) {
                    check("Food", "Export");
                } else if ("Vechile".equals(productCateogary)) {
                    check("Vechile", "Export");
                } else if ("Petroleum".equals(productCateogary)) {
                    check("Petroleum", "Export");
                } else if ("Jewellery".equals(productCateogary)) {
                    check("Jewellery", "Export");
                } else if ("Gagdets".equals(productCateogary)) {
                    check("Gagdets", "Export");
                } else if ("Clothes".equals(productCateogary)) {
                    check("Clothes", "Export");
                }
            }
        } catch (NullPointerException neException) {
            JOptionPane.showMessageDialog(null, "Please configure the radiobutton and Combobox",
                    "No Parameters Detected", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_cateogarySearchActionPerformed

    private void cateogary1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cateogary1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cateogary1ActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        //clearing the input fields
        nameFld.setText("");
        quantityFld.setText("");
        priceFld.setText("");
        dateFld.setText("");
        manuFld.setText("");
        buttonGroup2.clearSelection();

    }//GEN-LAST:event_clearBtnActionPerformed

    private void quantityFldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityFldKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();                                              //allowing only numeric value to be type on the following textfeild
        if (Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)) {
            quantityFld.setEditable(true);
        } else {
            quantityFld.setEditable(false);
        }
    }//GEN-LAST:event_quantityFldKeyPressed

    private void priceFldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceFldKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)) {
            priceFld.setEditable(true);
        } else {
            priceFld.setEditable(false);
        }
    }//GEN-LAST:event_priceFldKeyPressed

    private void searchFldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFldKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)) {
            searchFld.setEditable(true);
        } else {
            searchFld.setEditable(false);
        }
    }//GEN-LAST:event_searchFldKeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        //getting the selected row
        int selectedRow = jTable1.getSelectedRow();
        DefaultTableModel value = (DefaultTableModel) jTable1.getModel(); // using default table model to access our table

        //getting the values from table and insertig them to their respective fields
        nameFld.setText(value.getValueAt(selectedRow, 0).toString());

        String transType = value.getValueAt(selectedRow, 1).toString();
        if (transType.equals("Import")) {
            importRB.setSelected(true);
        } else {
            exportRB.setSelected(true);
        }

        manuFld.setText(value.getValueAt(selectedRow, 2).toString());

        String selectedCate = value.getValueAt(selectedRow, 3).toString();
        switch (selectedCate) {
            case "Food":
                inputCB.setSelectedIndex(0);
                break;
            case "Petroleum":
                inputCB.setSelectedIndex(1);
                break;
            case "Vehicle":
                inputCB.setSelectedIndex(2);
                break;
            case "Jewellery":
                inputCB.setSelectedIndex(3);
                break;
            case "Gadgets":
                inputCB.setSelectedIndex(4);
                break;
            case "Clothes":
                inputCB.setSelectedIndex(5);
                break;
        }

        quantityFld.setText(value.getValueAt(selectedRow, 4).toString());

        priceFld.setText(value.getValueAt(selectedRow, 5).toString());

        dateFld.setText(value.getValueAt(selectedRow, 6).toString());

    }//GEN-LAST:event_jTable1MouseClicked

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        //usign default table model to access our table
        DefaultTableModel changeValue = (DefaultTableModel) jTable1.getModel();
        int selectedRow = jTable1.getSelectedRow(); //getting the selected row

        if (selectedRow >= 0) {
            //changing the table details with new inputs
            changeValue.setValueAt(nameFld.getText(), selectedRow, 0);
            changeValue.setValueAt(buttonGroup2.getSelection().getActionCommand(), selectedRow, 1);
            changeValue.setValueAt(manuFld.getText(), selectedRow, 2);
            changeValue.setValueAt(inputCB.getSelectedItem(), selectedRow, 3);
            changeValue.setValueAt(quantityFld.getText(), selectedRow, 4);
            changeValue.setValueAt(priceFld.getText(), selectedRow, 5);
            changeValue.setValueAt(dateFld.getText(), selectedRow, 6);
            int priceCalc = Integer.parseInt(priceFld.getText()) * Integer.parseInt(quantityFld.getText());
            String totalPrice = Integer.toString(priceCalc);
            changeValue.setValueAt(totalPrice, selectedRow, 7);
            JOptionPane.showMessageDialog(null, "The details have been updated successfully.");
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row to update.");
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void nameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFldActionPerformed

    private void nameFldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameFldKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();  // getting the key pressed value.

        //validating characters 
        if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
            nameFld.setEditable(true); // setting textfield to editable
        } else {
            nameFld.setEditable(false); //setting textfield non editable
        }

    }//GEN-LAST:event_nameFldKeyPressed

    private void manuFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manuFldActionPerformed

    private void helpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpBtnActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_helpBtnActionPerformed

    private void openBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openBtnActionPerformed
        // TODO add your handling code here:
        try {
            String path = "E:\\Year 2\\Sem 1\\Emerging Programming Platforms and Technologies\\Coursework 1\\SAR_Transactions\\data.txt"; // the path of the required file
            File file = new File(path); // creating a file for the given fath

            //file reader to read the file required
            FileReader fReader = new FileReader(file);
            BufferedReader bReader = new BufferedReader(fReader);   //buffer reader to read what's in the file

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();        //default table model to identify our jtable and to add more functions
            Object[] lines = bReader.lines().toArray();        //table is all in object so creatring object datatype 

            for (int i = 0; i < lines.length; i++) {         //for loop utilization
                String[] row = lines[i].toString().split(",");      //spliting the data in the file into different parts
                model.addRow(row);          //adding the separated data in out jtable.
            }
            JOptionPane.showMessageDialog(null, "Load Successful! The data has been added at the bottom of the table.");

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "The file is not available.");
        }
    }//GEN-LAST:event_openBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
         // getting input data and storing them in local variables
        String name = (String) nameFld.getText();
        String quantity = (String) quantityFld.getText();              
        String price = (String) priceFld.getText();
        String date = (String) dateFld.getText();
        String manufacturer = (String) manuFld.getText();
        String productCateg = (String) inputCB.getSelectedItem();

        //checking the validity of the inputs
        if (name.isEmpty() || quantity.isEmpty() || price.isEmpty() || date.isEmpty() || manufacturer.isEmpty() || buttonGroup2.getSelection() == null) {
            JOptionPane.showMessageDialog(null, "Enter all the fields and select transaction type.");
        } else {
            String transType = buttonGroup2.getSelection().getActionCommand();
            int priceCalc = Integer.parseInt(priceFld.getText()) * Integer.parseInt(quantityFld.getText());
            String totalPrice = Integer.toString(priceCalc);

            String data[] = {name, transType, manufacturer, productCateg, quantity, price, date, totalPrice};   //storing the input data in an array

            DefaultTableModel modelAdd = (DefaultTableModel) jTable1.getModel();        //using default table model to access our table

            modelAdd.addRow(data);      //adding a row in the table with the data of the array.

            JOptionPane.showMessageDialog(null, "Data added successfully.");

            //clearing fields for new inputs.
            nameFld.setText("");
            quantityFld.setText("");
            priceFld.setText("");
            dateFld.setText("");
            manuFld.setText("");
            buttonGroup2.clearSelection();
            //exportRB.setSelected(false);
        }

    }//GEN-LAST:event_addBtnActionPerformed

    private void userGuideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userGuideActionPerformed
        // TODO add your handling code here:
        try {
            String path = "E:\\Year 2\\Sem 1\\Emerging Programming Platforms and Technologies\\Coursework 1\\SAR_Transactions\\Help.pdf";  //giving path of  a file
            File file = new File(path);

            if (file.exists()) { //if the file exists

                Desktop.getDesktop().open(file); //using desktop class to access the file in the desktop

            } else {
                JOptionPane.showMessageDialog(null, "File doesn't exist.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "File doesn't exist.");
        }
    }//GEN-LAST:event_userGuideActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SAR_Transactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SAR_Transactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SAR_Transactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SAR_Transactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SAR_Transactions().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cateogary1;
    private javax.swing.JButton cateogarySearch;
    private javax.swing.JButton clearBtn;
    private javax.swing.JTextField dateFld;
    private javax.swing.JMenuItem exitBtn;
    private javax.swing.JRadioButton exportRB;
    private javax.swing.JRadioButton exportRadio;
    private javax.swing.JMenu fileBtn;
    private javax.swing.JMenu helpBtn;
    private javax.swing.JRadioButton importRB;
    private javax.swing.JRadioButton importRadio;
    private javax.swing.JComboBox<String> inputCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton loadBtn;
    private javax.swing.JTextField manuFld;
    private javax.swing.JTextField nameFld;
    private javax.swing.JMenuItem openBtn;
    private javax.swing.JTextField priceFld;
    private javax.swing.JButton priceSearch;
    private javax.swing.JTextField quantityFld;
    private javax.swing.JTextField searchFld;
    private javax.swing.JButton updateBtn;
    private javax.swing.JMenuItem userGuide;
    // End of variables declaration//GEN-END:variables
}
